### ISSUE TITLE
Зацикливание, если точки первого треугольника лежат на одной прямой по X

### ISSUE THREAD

**Issue by Riflio** [Vemmy124/Delaunay-Triangulation-Algorithm#10]
Приветствую.
В общем, сабж.
Подскажите, пожалуйста, как тогда поступать?

Вот на таком наборе зацикливается:
`    _originPoints.append(Point2D(288*3, 149*3)); _originPoints.append(Point2D(288*3, 129*3)); _originPoints.append(Point2D(270*3, 133*3)); _originPoints.append(Point2D(256*3, 141*3)); _originPoints.append(Point2D(256*3, 157*3)); _originPoints.append(Point2D(246*3, 157*3));
    _originPoints.append(Point2D(236*3, 169*3)); _originPoints.append(Point2D(228*3, 169*3)); _originPoints.append(Point2D(228*3, 161*3)); _originPoints.append(Point2D(220*3, 169*3)); _originPoints.append(Point2D(212*3, 169*3)); _originPoints.append(Point2D(204*3, 169*3));
    _originPoints.append(Point2D(196*3, 169*3)); _originPoints.append(Point2D(188*3, 169*3)); _originPoints.append(Point2D(196*3, 161*3)); _originPoints.append(Point2D(188*3, 145*3)); _originPoints.append(Point2D(172*3, 145*3)); _originPoints.append(Point2D(164*3, 145*3));
    _originPoints.append(Point2D(156*3, 145*3)); _originPoints.append(Point2D(148*3, 145*3)); _originPoints.append(Point2D(140*3, 145*3)); _originPoints.append(Point2D(148*3, 169*3)); _originPoints.append(Point2D(164*3, 169*3)); _originPoints.append(Point2D(172*3, 169*3));
    _originPoints.append(Point2D(156*3, 169*3)); _originPoints.append(Point2D(140*3, 169*3)); _originPoints.append(Point2D(132*3, 169*3)); _originPoints.append(Point2D(124*3, 169*3)); _originPoints.append(Point2D(116*3, 161*3)); _originPoints.append(Point2D(104*3, 153*3));
    _originPoints.append(Point2D(104*3, 161*3)); _originPoints.append(Point2D(104*3, 169*3)); _originPoints.append(Point2D(90*3, 165*3)); _originPoints.append(Point2D(80*3, 157*3)); _originPoints.append(Point2D(64*3, 157*3)); _originPoints.append(Point2D(64*3, 165*3));
    _originPoints.append(Point2D(56*3, 169*3)); _originPoints.append(Point2D(56*3, 161*3)); _originPoints.append(Point2D(56*3, 153*3)); _originPoints.append(Point2D(56*3, 145*3)); _originPoints.append(Point2D(56*3, 137*3)); _originPoints.append(Point2D(56*3, 129*3));
    _originPoints.append(Point2D(56*3, 121*3)); _originPoints.append(Point2D(40*3, 121*3)); _originPoints.append(Point2D(40*3, 129*3)); _originPoints.append(Point2D(40*3, 137*3)); _originPoints.append(Point2D(40*3, 145*3)); _originPoints.append(Point2D(40*3, 153*3));
    _originPoints.append(Point2D(40*3, 161*3)); _originPoints.append(Point2D(40*3, 169*3)); _originPoints.append(Point2D(32*3, 169*3)); _originPoints.append(Point2D(32*3, 161*3)); _originPoints.append(Point2D(32*3, 153*3)); _originPoints.append(Point2D(32*3, 145*3));
    _originPoints.append(Point2D(32*3, 137*3)); _originPoints.append(Point2D(32*3, 129*3)); _originPoints.append(Point2D(32*3, 121*3)); _originPoints.append(Point2D(32*3, 113*3)); _originPoints.append(Point2D(40*3, 113*3)); _originPoints.append(Point2D(56*3, 113*3));
    _originPoints.append(Point2D(56*3, 105*3)); _originPoints.append(Point2D(48*3, 99*3)); _originPoints.append(Point2D(40*3, 99*3)); _originPoints.append(Point2D(32*3, 97*3)); _originPoints.append(Point2D(32*3, 89*3)); _originPoints.append(Point2D(24*3, 89*3));
    _originPoints.append(Point2D(16*3, 97*3)); _originPoints.append(Point2D(16*3, 109*3)); _originPoints.append(Point2D(8*3, 109*3)); _originPoints.append(Point2D(8*3, 97*3)); _originPoints.append(Point2D(8*3, 89*3)); _originPoints.append(Point2D(8*3, 81*3));
    _originPoints.append(Point2D(8*3, 73*3)); _originPoints.append(Point2D(8*3, 65*3)); _originPoints.append(Point2D(8*3, 57*3)); _originPoints.append(Point2D(16*3, 57*3)); _originPoints.append(Point2D(8*3, 49*3)); _originPoints.append(Point2D(8*3, 41*3));
    _originPoints.append(Point2D(24*3, 45*3)); _originPoints.append(Point2D(32*3, 41*3)); _originPoints.append(Point2D(32*3, 49*3)); _originPoints.append(Point2D(32*3, 57*3)); _originPoints.append(Point2D(32*3, 65*3)); _originPoints.append(Point2D(32*3, 73*3));
    _originPoints.append(Point2D(32*3, 81*3)); _originPoints.append(Point2D(40*3, 83*3)); _originPoints.append(Point2D(40*3, 73*3)); _originPoints.append(Point2D(40*3, 63*3)); _originPoints.append(Point2D(40*3, 51*3)); _originPoints.append(Point2D(44*3, 43*3));
    _originPoints.append(Point2D(44*3, 35*3)); _originPoints.append(Point2D(44*3, 27*3)); _originPoints.append(Point2D(32*3, 25*3)); _originPoints.append(Point2D(24*3, 25*3)); _originPoints.append(Point2D(16*3, 25*3)); _originPoints.append(Point2D(16*3, 17*3));
    _originPoints.append(Point2D(24*3, 17*3)); _originPoints.append(Point2D(32*3, 17*3)); _originPoints.append(Point2D(44*3, 11*3)); _originPoints.append(Point2D(56*3, 9*3)); _originPoints.append(Point2D(56*3, 17*3)); _originPoints.append(Point2D(56*3, 25*3));
    _originPoints.append(Point2D(56*3, 33*3)); _originPoints.append(Point2D(56*3, 41*3)); _originPoints.append(Point2D(64*3, 41*3)); _originPoints.append(Point2D(72*3, 41*3)); _originPoints.append(Point2D(72*3, 49*3)); _originPoints.append(Point2D(56*3, 49*3));
    _originPoints.append(Point2D(48*3, 51*3)); _originPoints.append(Point2D(56*3, 57*3)); _originPoints.append(Point2D(56*3, 65*3)); _originPoints.append(Point2D(48*3, 63*3)); _originPoints.append(Point2D(48*3, 73*3)); _originPoints.append(Point2D(56*3, 73*3));
    _originPoints.append(Point2D(56*3, 81*3)); _originPoints.append(Point2D(48*3, 83*3)); _originPoints.append(Point2D(56*3, 89*3)); _originPoints.append(Point2D(56*3, 97*3)); _originPoints.append(Point2D(104*3, 97*3)); _originPoints.append(Point2D(104*3, 105*3));
    _originPoints.append(Point2D(104*3, 113*3)); _originPoints.append(Point2D(104*3, 121*3)); _originPoints.append(Point2D(104*3, 129*3)); _originPoints.append(Point2D(104*3, 137*3)); _originPoints.append(Point2D(104*3, 145*3)); _originPoints.append(Point2D(116*3, 145*3));
    _originPoints.append(Point2D(124*3, 145*3)); _originPoints.append(Point2D(132*3, 145*3)); _originPoints.append(Point2D(132*3, 137*3)); _originPoints.append(Point2D(140*3, 137*3)); _originPoints.append(Point2D(148*3, 137*3)); _originPoints.append(Point2D(156*3, 137*3));
    _originPoints.append(Point2D(164*3, 137*3)); _originPoints.append(Point2D(172*3, 125*3)); _originPoints.append(Point2D(172*3, 117*3)); _originPoints.append(Point2D(172*3, 109*3)); _originPoints.append(Point2D(172*3, 101*3)); _originPoints.append(Point2D(172*3, 93*3));
    _originPoints.append(Point2D(172*3, 85*3)); _originPoints.append(Point2D(180*3, 85*3)); _originPoints.append(Point2D(180*3, 77*3)); _originPoints.append(Point2D(180*3, 69*3)); _originPoints.append(Point2D(180*3, 61*3)); _originPoints.append(Point2D(180*3, 53*3));
    _originPoints.append(Point2D(172*3, 53*3)); _originPoints.append(Point2D(172*3, 61*3)); _originPoints.append(Point2D(172*3, 69*3)); _originPoints.append(Point2D(172*3, 77*3)); _originPoints.append(Point2D(164*3, 81*3)); _originPoints.append(Point2D(148*3, 85*3));
    _originPoints.append(Point2D(124*3, 85*3)); _originPoints.append(Point2D(124*3, 93*3)); _originPoints.append(Point2D(124*3, 109*3)); _originPoints.append(Point2D(124*3, 125*3)); _originPoints.append(Point2D(124*3, 117*3)); _originPoints.append(Point2D(124*3, 101*3));
    _originPoints.append(Point2D(104*3, 89*3)); _originPoints.append(Point2D(104*3, 81*3)); _originPoints.append(Point2D(104*3, 73*3)); _originPoints.append(Point2D(104*3, 65*3)); _originPoints.append(Point2D(104*3, 49*3)); _originPoints.append(Point2D(104*3, 41*3));
    _originPoints.append(Point2D(104*3, 33*3)); _originPoints.append(Point2D(104*3, 25*3)); _originPoints.append(Point2D(104*3, 17*3)); _originPoints.append(Point2D(92*3, 9*3)); _originPoints.append(Point2D(80*3, 9*3)); _originPoints.append(Point2D(72*3, 9*3));
    _originPoints.append(Point2D(64*3, 21*3)); _originPoints.append(Point2D(72*3, 25*3)); _originPoints.append(Point2D(80*3, 25*3)); _originPoints.append(Point2D(80*3, 25*3)); _originPoints.append(Point2D(80*3, 41*3)); _originPoints.append(Point2D(88*3, 49*3));
    _originPoints.append(Point2D(104*3, 57*3)); _originPoints.append(Point2D(124*3, 69*3)); _originPoints.append(Point2D(124*3, 77*3)); _originPoints.append(Point2D(132*3, 81*3)); _originPoints.append(Point2D(140*3, 65*3)); _originPoints.append(Point2D(132*3, 61*3));
    _originPoints.append(Point2D(124*3, 61*3)); _originPoints.append(Point2D(124*3, 53*3)); _originPoints.append(Point2D(124*3, 45*3)); _originPoints.append(Point2D(124*3, 37*3)); _originPoints.append(Point2D(124*3, 29*3)); _originPoints.append(Point2D(132*3, 21*3));
    _originPoints.append(Point2D(124*3, 21*3)); _originPoints.append(Point2D(120*3, 9*3)); _originPoints.append(Point2D(128*3, 9*3)); _originPoints.append(Point2D(136*3, 9*3)); _originPoints.append(Point2D(148*3, 9*3)); _originPoints.append(Point2D(162*3, 9*3));
    _originPoints.append(Point2D(156*3, 25*3)); _originPoints.append(Point2D(172*3, 21*3)); _originPoints.append(Point2D(180*3, 21*3)); _originPoints.append(Point2D(180*3, 29*3)); _originPoints.append(Point2D(172*3, 29*3)); _originPoints.append(Point2D(172*3, 37*3));
    _originPoints.append(Point2D(172*3, 45*3)); _originPoints.append(Point2D(180*3, 45*3)); _originPoints.append(Point2D(180*3, 37*3)); _originPoints.append(Point2D(188*3, 41*3)); _originPoints.append(Point2D(196*3, 49*3)); _originPoints.append(Point2D(204*3, 57*3));
    _originPoints.append(Point2D(212*3, 65*3)); _originPoints.append(Point2D(220*3, 73*3)); _originPoints.append(Point2D(228*3, 69*3)); _originPoints.append(Point2D(228*3, 77*3)); _originPoints.append(Point2D(236*3, 77*3)); _originPoints.append(Point2D(236*3, 69*3));
    _originPoints.append(Point2D(236*3, 61*3)); _originPoints.append(Point2D(228*3, 61*3)); _originPoints.append(Point2D(228*3, 53*3)); _originPoints.append(Point2D(236*3, 53*3)); _originPoints.append(Point2D(236*3, 45*3)); _originPoints.append(Point2D(228*3, 45*3));
    _originPoints.append(Point2D(228*3, 37*3)); _originPoints.append(Point2D(236*3, 37*3)); _originPoints.append(Point2D(236*3, 29*3)); _originPoints.append(Point2D(228*3, 29*3)); _originPoints.append(Point2D(228*3, 21*3)); _originPoints.append(Point2D(236*3, 21*3));
    _originPoints.append(Point2D(252*3, 21*3)); _originPoints.append(Point2D(260*3, 29*3)); _originPoints.append(Point2D(260*3, 37*3)); _originPoints.append(Point2D(260*3, 45*3)); _originPoints.append(Point2D(260*3, 53*3)); _originPoints.append(Point2D(260*3, 61*3));
    _originPoints.append(Point2D(260*3, 69*3)); _originPoints.append(Point2D(260*3, 77*3)); _originPoints.append(Point2D(276*3, 77*3)); _originPoints.append(Point2D(276*3, 69*3)); _originPoints.append(Point2D(276*3, 61*3)); _originPoints.append(Point2D(276*3, 53*3));
    _originPoints.append(Point2D(284*3, 53*3)); _originPoints.append(Point2D(284*3, 61*3)); _originPoints.append(Point2D(284*3, 69*3)); _originPoints.append(Point2D(284*3, 77*3)); _originPoints.append(Point2D(284*3, 85*3)); _originPoints.append(Point2D(284*3, 93*3));
    _originPoints.append(Point2D(284*3, 101*3)); _originPoints.append(Point2D(288*3, 109*3)); _originPoints.append(Point2D(280*3, 109*3)); _originPoints.append(Point2D(276*3, 101*3)); _originPoints.append(Point2D(276*3, 93*3)); _originPoints.append(Point2D(276*3, 85*3));
    _originPoints.append(Point2D(268*3, 97*3)); _originPoints.append(Point2D(260*3, 109*3)); _originPoints.append(Point2D(252*3, 101*3)); _originPoints.append(Point2D(260*3, 93*3)); _originPoints.append(Point2D(260*3, 85*3)); _originPoints.append(Point2D(236*3, 85*3));
    _originPoints.append(Point2D(228*3, 85*3)); _originPoints.append(Point2D(228*3, 93*3)); _originPoints.append(Point2D(236*3, 93*3)); _originPoints.append(Point2D(236*3, 101*3)); _originPoints.append(Point2D(228*3, 101*3)); _originPoints.append(Point2D(228*3, 109*3));
    _originPoints.append(Point2D(228*3, 117*3)); _originPoints.append(Point2D(228*3, 125*3)); _originPoints.append(Point2D(220*3, 125*3)); _originPoints.append(Point2D(212*3, 117*3)); _originPoints.append(Point2D(204*3, 109*3)); _originPoints.append(Point2D(196*3, 101*3));
    _originPoints.append(Point2D(188*3, 93*3)); _originPoints.append(Point2D(180*3, 93*3)); _originPoints.append(Point2D(180*3, 101*3)); _originPoints.append(Point2D(180*3, 109*3)); _originPoints.append(Point2D(180*3, 117*3)); _originPoints.append(Point2D(180*3, 125*3));
    _originPoints.append(Point2D(196*3, 145*3)); _originPoints.append(Point2D(204*3, 145*3)); _originPoints.append(Point2D(212*3, 145*3)); _originPoints.append(Point2D(220*3, 145*3)); _originPoints.append(Point2D(228*3, 145*3)); _originPoints.append(Point2D(236*3, 145*3));
    _originPoints.append(Point2D(246*3, 141*3)); _originPoints.append(Point2D(252*3, 125*3)); _originPoints.append(Point2D(260*3, 129*3)); _originPoints.append(Point2D(280*3, 133*3));
`

**Comment by Vemmy124** [comment]
Доброго времени суток! Прошу прощения за долгий ответ.

Там 8 точек имеют минимальную координату, честно говоря, я не очень понимаю, как должна выглядеть правильная триангуляция. Если устраивает любая, то самое простое решение - произодить сортировку в произвольном направлении, то есть в компараторе написать
`a * (lhs.x - rhs.x) + b * (lhs.y - rhs.y) < 0`, где a, b выбрать произвольно от -1 до 1, например.

Спасибо за фидбэк, я подумаю, как в целом в коде обойти эту проблему.

**Comment by Riflio** [comment]
Здравствуйте! Ничего страшного, спасибо =)
